parameters:
    moviedb.api_key: '%env(MOVIEDB_API_KEY)%'
    moviedb.base_url: '%env(MOVIEDB_API_URL)%'
    moviedb.image_base_url: '%env(MOVIEDB_IMAGE_BASE_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'